#pragma once
// GENERATED by tools/gen_style_h.py from tools/style.json - do not edit by hand.
#include <stdint.h>

struct WidthPt { uint8_t zoom; float px; };
struct LineStyle { uint16_t color; uint8_t n_w; WidthPt w[4]; uint8_t dash_on, dash_off; uint16_t dash_color; };
struct RoadStyle { uint16_t fill, casing; uint8_t casing_from_zoom; uint8_t n_w; WidthPt w[4]; uint8_t dash_on, dash_off; };
struct LabelStyle { uint16_t color; uint8_t size; };

static const uint16_t STYLE_BG = 0xF77D;
static const uint16_t STYLE_WATER = 0xAE9B;
static const uint16_t STYLE_LANDUSE[10] = { 0xCF38, 0xAE93, 0xEF1B, 0xE6DA, 0xEF9A, 0xCED8, 0xF75B, 0xBF16, 0xEF3C, 0xEF7D };
static const uint16_t STYLE_BUILDING = 0xDE99;
static const uint16_t STYLE_BUILDING_OUTLINE = 0xC5D6;
static const uint8_t  STYLE_BUILDING_OUTLINE_FROM_ZOOM = 16;

static const LineStyle STYLE_WATERWAY[3] = {
  { 0xAE9B, 3, {{11, 1.0f}, {14, 2.5f}, {16, 5.0f}}, 0, 0, 0xFFFF },
  { 0xAE9B, 2, {{13, 1.0f}, {16, 3.0f}}, 0, 0, 0xFFFF },
  { 0xAE9B, 2, {{14, 0.8f}, {16, 1.5f}}, 0, 0, 0xFFFF }
};
static const LineStyle STYLE_RAIL[3] = {
  { 0x8C51, 3, {{11, 0.8f}, {14, 1.5f}, {16, 2.5f}}, 6, 6, 0xFFFF },
  { 0x7A73, 3, {{12, 0.8f}, {14, 1.5f}, {16, 2.5f}}, 0, 0, 0xFFFF },
  { 0x9CD3, 2, {{14, 0.8f}, {16, 1.5f}}, 0, 0, 0xFFFF }
};
static const LineStyle STYLE_AEROWAY[2] = {
  { 0xBDF8, 3, {{12, 2.0f}, {14, 6.0f}, {16, 20.0f}}, 0, 0, 0xFFFF },
  { 0xBDF8, 3, {{12, 0.8f}, {14, 2.0f}, {16, 6.0f}}, 0, 0, 0xFFFF }
};
static const RoadStyle STYLE_ROAD[9] = {
  { 0xEC94, 0xC26D, 12, 4, {{10, 1.5f}, {12, 3.0f}, {14, 6.0f}, {16, 12.0f}}, 0, 0 },
  { 0xFD93, 0xCB49, 12, 4, {{10, 1.2f}, {12, 2.5f}, {14, 5.0f}, {16, 10.0f}}, 0, 0 },
  { 0xFEB4, 0xCD09, 13, 4, {{11, 1.0f}, {13, 2.5f}, {15, 5.0f}, {16, 9.0f}}, 0, 0 },
  { 0xF7D7, 0xBDCC, 14, 3, {{12, 0.8f}, {14, 2.0f}, {16, 7.0f}}, 0, 0 },
  { 0xFFFF, 0xB553, 15, 3, {{13, 0.8f}, {15, 2.5f}, {16, 6.0f}}, 0, 0 },
  { 0xFFFF, 0xBD95, 15, 3, {{14, 0.9f}, {15, 1.8f}, {16, 4.5f}}, 0, 0 },
  { 0xFFFF, 0xC5F6, 16, 2, {{15, 0.8f}, {16, 2.5f}}, 0, 0 },
  { 0xCD31, 0xFFFF, 99, 2, {{15, 0.6f}, {16, 1.2f}}, 3, 2 },
  { 0xDEFB, 0xBDD7, 99, 2, {{15, 0.6f}, {16, 1.5f}}, 0, 0 }
};

static const LabelStyle STYLE_PLACE[5] = { {0x2104, 16}, {0x2104, 14}, {0x4228, 12}, {0x52AA, 12}, {0x52AA, 12} };
static const LabelStyle STYLE_POI = {0x6A67, 12};
static const uint16_t STYLE_HALO = 0xF77D;

// Piecewise-linear width in px for a fractional zoom; grows 1.6x per zoom past the last point.
static inline float style_width(const WidthPt* w, uint8_t n, float zoom) {
  if (n == 0) return 0;
  if (zoom <= w[0].zoom) return w[0].px;
  for (uint8_t i = 1; i < n; i++)
    if (zoom <= w[i].zoom) {
      float t = (zoom - w[i - 1].zoom) / (float)(w[i].zoom - w[i - 1].zoom);
      return w[i - 1].px + t * (w[i].px - w[i - 1].px);
    }
  float over = zoom - w[n - 1].zoom;
  float f = 1.0f; while (over >= 1.0f) { f *= 1.6f; over -= 1.0f; } f *= 1.0f + 0.6f * over;
  return w[n - 1].px * f;
}
