#!/usr/bin/env python3
"""style.json -> ../maps/style.h  (keeps the device style in sync with the shared JSON)."""
import json, os, sys
here = os.path.dirname(os.path.abspath(__file__))
S = json.load(open(os.path.join(here, 'style.json')))

def rgb565(h):
    r, g, b = int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)
    return f"0x{((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3):04X}"

def width_curve(w):
    zs = sorted(w, key=int)
    pts = ", ".join(f"{{{int(z)}, {float(w[z])}f}}" for z in zs)
    return len(zs), pts

out = []
out.append("#pragma once\n// GENERATED by tools/gen_style_h.py from tools/style.json - do not edit by hand.\n#include <stdint.h>\n")
out.append("struct WidthPt { uint8_t zoom; float px; };")
out.append("struct LineStyle { uint16_t color; uint8_t n_w; WidthPt w[4]; uint8_t dash_on, dash_off; uint16_t dash_color; };")
out.append("struct RoadStyle { uint16_t fill, casing; uint8_t casing_from_zoom; uint8_t n_w; WidthPt w[4]; uint8_t dash_on, dash_off; };")
out.append("struct LabelStyle { uint16_t color; uint8_t size; };\n")
out.append(f"static const uint16_t STYLE_BG = {rgb565(S['background'])};")
out.append(f"static const uint16_t STYLE_WATER = {rgb565(S['water']['fill'])};")
lu = S['landuse']; n = max(int(k) for k in lu) + 1
out.append(f"static const uint16_t STYLE_LANDUSE[{n}] = {{ " + ", ".join(rgb565(lu[str(i)]['fill']) if str(i) in lu else '0xFFFF' for i in range(n)) + " };")
b = S['building']
out.append(f"static const uint16_t STYLE_BUILDING = {rgb565(b['fill'])};")
out.append(f"static const uint16_t STYLE_BUILDING_OUTLINE = {rgb565(b['outline'])};")
out.append(f"static const uint8_t  STYLE_BUILDING_OUTLINE_FROM_ZOOM = {b['outline_from_zoom']};\n")

def line_table(name, tbl):
    n = max(int(k) for k in tbl) + 1
    rows = []
    for i in range(n):
        t = tbl.get(str(i))
        if not t:
            rows.append("  { 0xFFFF, 0, {}, 0, 0, 0 }"); continue
        nw, pts = width_curve(t['width'])
        dash = t.get('dash', [0, 0])
        rows.append(f"  {{ {rgb565(t['stroke'])}, {nw}, {{{pts}}}, {dash[0]}, {dash[1]}, {rgb565(t['dash_color']) if 'dash_color' in t else '0xFFFF'} }}")
    out.append(f"static const LineStyle {name}[{n}] = {{\n" + ",\n".join(rows) + "\n};")

line_table('STYLE_WATERWAY', S['waterway'])
line_table('STYLE_RAIL', S['rail'])
line_table('STYLE_AEROWAY', S['aeroway'])
rd = S['road']; n = max(int(k) for k in rd) + 1
rows = []
for i in range(n):
    t = rd[str(i)]
    nw, pts = width_curve(t['width'])
    dash = t.get('dash', [0, 0])
    rows.append(f"  {{ {rgb565(t['fill'])}, {rgb565(t['casing'])}, {t.get('casing_from_zoom', 99)}, {nw}, {{{pts}}}, {dash[0]}, {dash[1]} }}")
out.append(f"static const RoadStyle STYLE_ROAD[{n}] = {{\n" + ",\n".join(rows) + "\n};\n")
pl = S['label']['place']; n = max(int(k) for k in pl) + 1
out.append(f"static const LabelStyle STYLE_PLACE[{n}] = {{ " + ", ".join(f"{{{rgb565(pl[str(i)]['color'])}, {pl[str(i)]['size']}}}" for i in range(n)) + " };")
out.append(f"static const LabelStyle STYLE_POI = {{{rgb565(S['label']['poi']['color'])}, {S['label']['poi']['size']}}};")
out.append(f"static const uint16_t STYLE_HALO = {rgb565(S['label']['halo'])};\n")
out.append("""// Piecewise-linear width in px for a fractional zoom; grows 1.6x per zoom past the last point.
static inline float style_width(const WidthPt* w, uint8_t n, float zoom) {
  if (n == 0) return 0;
  if (zoom <= w[0].zoom) return w[0].px;
  for (uint8_t i = 1; i < n; i++)
    if (zoom <= w[i].zoom) {
      float t = (zoom - w[i - 1].zoom) / (float)(w[i].zoom - w[i - 1].zoom);
      return w[i - 1].px + t * (w[i].px - w[i - 1].px);
    }
  float over = zoom - w[n - 1].zoom;
  float f = 1.0f; while (over >= 1.0f) { f *= 1.6f; over -= 1.0f; } f *= 1.0f + 0.6f * over;
  return w[n - 1].px * f;
}""")
open(os.path.join(here, '..', 'maps', 'style.h'), 'w').write("\n".join(out) + "\n")
print("wrote maps/style.h")
